import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

// Pokémon interface
interface Pokemon {
  id: string;
  name: string;
  type: string;
  power: number;
  life: number;
  image: string;
}

@Component({
  selector: 'app-pokemon',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './pokemons.component.html',
  styleUrls: ['./pokemons.component.css'],
})
export class PokemonComponent implements OnInit {
  pokemons: Pokemon[] = [];
  loading = true;

  constructor() {}

  async ngOnInit() {
    await this.loadPokemons();
  }

  async loadPokemons() {
    this.loading = true;

    // Sample 50 Pokémon data
    this.pokemons = [
      {
        id: '1',
        name: 'Bulbasaur',
        type: 'Grass/Poison',
        power: 49,
        life: 45,
        image: 'https://img.pokemondb.net/artwork/large/bulbasaur.jpg',
      },
      {
        id: '2',
        name: 'Ivysaur',
        type: 'Grass/Poison',
        power: 62,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/ivysaur.jpg',
      },
      {
        id: '3',
        name: 'Venusaur',
        type: 'Grass/Poison',
        power: 82,
        life: 80,
        image: 'https://img.pokemondb.net/artwork/large/venusaur.jpg',
      },
      {
        id: '4',
        name: 'Charmander',
        type: 'Fire',
        power: 52,
        life: 39,
        image: 'https://img.pokemondb.net/artwork/large/charmander.jpg',
      },
      {
        id: '5',
        name: 'Charmeleon',
        type: 'Fire',
        power: 64,
        life: 58,
        image: 'https://img.pokemondb.net/artwork/large/charmeleon.jpg',
      },
      {
        id: '6',
        name: 'Charizard',
        type: 'Fire/Flying',
        power: 84,
        life: 78,
        image: 'https://img.pokemondb.net/artwork/large/charizard.jpg',
      },
      {
        id: '7',
        name: 'Squirtle',
        type: 'Water',
        power: 48,
        life: 44,
        image: 'https://img.pokemondb.net/artwork/large/squirtle.jpg',
      },
      {
        id: '8',
        name: 'Wartortle',
        type: 'Water',
        power: 63,
        life: 59,
        image: 'https://img.pokemondb.net/artwork/large/wartortle.jpg',
      },
      {
        id: '9',
        name: 'Blastoise',
        type: 'Water',
        power: 83,
        life: 79,
        image: 'https://img.pokemondb.net/artwork/large/blastoise.jpg',
      },
      {
        id: '10',
        name: 'Caterpie',
        type: 'Bug',
        power: 30,
        life: 45,
        image: 'https://img.pokemondb.net/artwork/large/caterpie.jpg',
      },
      {
        id: '11',
        name: 'Metapod',
        type: 'Bug',
        power: 20,
        life: 50,
        image: 'https://img.pokemondb.net/artwork/large/metapod.jpg',
      },
      {
        id: '12',
        name: 'Butterfree',
        type: 'Bug/Flying',
        power: 45,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/butterfree.jpg',
      },
      {
        id: '13',
        name: 'Weedle',
        type: 'Bug/Poison',
        power: 35,
        life: 40,
        image: 'https://img.pokemondb.net/artwork/large/weedle.jpg',
      },
      {
        id: '14',
        name: 'Kakuna',
        type: 'Bug/Poison',
        power: 25,
        life: 45,
        image: 'https://img.pokemondb.net/artwork/large/kakuna.jpg',
      },
      {
        id: '15',
        name: 'Beedrill',
        type: 'Bug/Poison',
        power: 90,
        life: 65,
        image: 'https://img.pokemondb.net/artwork/large/beedrill.jpg',
      },
      {
        id: '16',
        name: 'Pidgey',
        type: 'Normal/Flying',
        power: 45,
        life: 40,
        image: 'https://img.pokemondb.net/artwork/large/pidgey.jpg',
      },
      {
        id: '17',
        name: 'Pidgeotto',
        type: 'Normal/Flying',
        power: 60,
        life: 63,
        image: 'https://img.pokemondb.net/artwork/large/pidgeotto.jpg',
      },
      {
        id: '18',
        name: 'Pidgeot',
        type: 'Normal/Flying',
        power: 80,
        life: 83,
        image: 'https://img.pokemondb.net/artwork/large/pidgeot.jpg',
      },
      {
        id: '19',
        name: 'Rattata',
        type: 'Normal',
        power: 56,
        life: 30,
        image: 'https://img.pokemondb.net/artwork/large/rattata.jpg',
      },
      {
        id: '20',
        name: 'Raticate',
        type: 'Normal',
        power: 81,
        life: 55,
        image: 'https://img.pokemondb.net/artwork/large/raticate.jpg',
      },
      {
        id: '21',
        name: 'Spearow',
        type: 'Normal/Flying',
        power: 60,
        life: 40,
        image: 'https://img.pokemondb.net/artwork/large/spearow.jpg',
      },
      {
        id: '22',
        name: 'Fearow',
        type: 'Normal/Flying',
        power: 90,
        life: 65,
        image: 'https://img.pokemondb.net/artwork/large/fearow.jpg',
      },
      {
        id: '23',
        name: 'Ekans',
        type: 'Poison',
        power: 60,
        life: 35,
        image: 'https://img.pokemondb.net/artwork/large/ekans.jpg',
      },
      {
        id: '24',
        name: 'Arbok',
        type: 'Poison',
        power: 85,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/arbok.jpg',
      },
      {
        id: '25',
        name: 'Pikachu',
        type: 'Electric',
        power: 55,
        life: 35,
        image: 'https://img.pokemondb.net/artwork/large/pikachu.jpg',
      },
      {
        id: '26',
        name: 'Raichu',
        type: 'Electric',
        power: 90,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/raichu.jpg',
      },
      {
        id: '27',
        name: 'Sandshrew',
        type: 'Ground',
        power: 75,
        life: 50,
        image: 'https://img.pokemondb.net/artwork/large/sandshrew.jpg',
      },
      {
        id: '28',
        name: 'Sandslash',
        type: 'Ground',
        power: 100,
        life: 75,
        image: 'https://img.pokemondb.net/artwork/large/sandslash.jpg',
      },
      {
        id: '29',
        name: 'Nidoran♀',
        type: 'Poison',
        power: 47,
        life: 55,
        image: 'https://img.pokemondb.net/artwork/large/nidoran-f.jpg',
      },
      {
        id: '30',
        name: 'Nidorina',
        type: 'Poison',
        power: 62,
        life: 70,
        image: 'https://img.pokemondb.net/artwork/large/nidorina.jpg',
      },
      {
        id: '31',
        name: 'Nidoqueen',
        type: 'Poison/Ground',
        power: 92,
        life: 90,
        image: 'https://img.pokemondb.net/artwork/large/nidoqueen.jpg',
      },
      {
        id: '32',
        name: 'Nidoran♂',
        type: 'Poison',
        power: 57,
        life: 46,
        image: 'https://img.pokemondb.net/artwork/large/nidoran-m.jpg',
      },
      {
        id: '33',
        name: 'Nidorino',
        type: 'Poison',
        power: 72,
        life: 61,
        image: 'https://img.pokemondb.net/artwork/large/nidorino.jpg',
      },
      {
        id: '34',
        name: 'Nidoking',
        type: 'Poison/Ground',
        power: 102,
        life: 81,
        image: 'https://img.pokemondb.net/artwork/large/nidoking.jpg',
      },
      {
        id: '35',
        name: 'Clefairy',
        type: 'Fairy',
        power: 45,
        life: 70,
        image: 'https://img.pokemondb.net/artwork/large/clefairy.jpg',
      },
      {
        id: '36',
        name: 'Clefable',
        type: 'Fairy',
        power: 70,
        life: 95,
        image: 'https://img.pokemondb.net/artwork/large/clefable.jpg',
      },
      {
        id: '37',
        name: 'Vulpix',
        type: 'Fire',
        power: 41,
        life: 38,
        image: 'https://img.pokemondb.net/artwork/large/vulpix.jpg',
      },
      {
        id: '38',
        name: 'Ninetales',
        type: 'Fire',
        power: 76,
        life: 73,
        image: 'https://img.pokemondb.net/artwork/large/ninetales.jpg',
      },
      {
        id: '39',
        name: 'Jigglypuff',
        type: 'Normal/Fairy',
        power: 45,
        life: 115,
        image: 'https://img.pokemondb.net/artwork/large/jigglypuff.jpg',
      },
      {
        id: '40',
        name: 'Wigglytuff',
        type: 'Normal/Fairy',
        power: 70,
        life: 140,
        image: 'https://img.pokemondb.net/artwork/large/wigglytuff.jpg',
      },
      {
        id: '41',
        name: 'Zubat',
        type: 'Poison/Flying',
        power: 45,
        life: 40,
        image: 'https://img.pokemondb.net/artwork/large/zubat.jpg',
      },
      {
        id: '42',
        name: 'Golbat',
        type: 'Poison/Flying',
        power: 80,
        life: 75,
        image: 'https://img.pokemondb.net/artwork/large/golbat.jpg',
      },
      {
        id: '43',
        name: 'Oddish',
        type: 'Grass/Poison',
        power: 50,
        life: 45,
        image: 'https://img.pokemondb.net/artwork/large/oddish.jpg',
      },
      {
        id: '44',
        name: 'Gloom',
        type: 'Grass/Poison',
        power: 65,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/gloom.jpg',
      },
      {
        id: '45',
        name: 'Vileplume',
        type: 'Grass/Poison',
        power: 80,
        life: 75,
        image: 'https://img.pokemondb.net/artwork/large/vileplume.jpg',
      },
      {
        id: '46',
        name: 'Paras',
        type: 'Bug/Grass',
        power: 70,
        life: 35,
        image: 'https://img.pokemondb.net/artwork/large/paras.jpg',
      },
      {
        id: '47',
        name: 'Parasect',
        type: 'Bug/Grass',
        power: 95,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/parasect.jpg',
      },
      {
        id: '48',
        name: 'Venonat',
        type: 'Bug/Poison',
        power: 55,
        life: 60,
        image: 'https://img.pokemondb.net/artwork/large/venonat.jpg',
      },
      {
        id: '49',
        name: 'Venomoth',
        type: 'Bug/Poison',
        power: 65,
        life: 70,
        image: 'https://img.pokemondb.net/artwork/large/venomoth.jpg',
      },
      {
        id: '50',
        name: 'Diglett',
        type: 'Ground',
        power: 55,
        life: 10,
        image: 'https://img.pokemondb.net/artwork/large/diglett.jpg',
      },
    ];

    this.loading = false;
  }
}
